import type { Metadata } from 'next'
import {Gothic_A1} from 'next/font/google'
import './globals.css'
import React from "react";
import { Analytics } from '@vercel/analytics/react';

const yoGothic = Gothic_A1({ subsets: ['latin'], weight : ['400', "500", "600", "700"] })

export const metadata: Metadata = {
    title: 'Portfolio',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body className={yoGothic.className}>
            {children}
            <Analytics />
        </body>
        </html>
    )
}
